FROM elixir:1.5.2-alpine
RUN apk add --update nodejs nodejs-npm
RUN apk add --update inotify-tools

RUN adduser -D myuser
ENV MIX_ENV=dev

RUN mkdir /home/myuser/code
WORKDIR /home/myuser/code

COPY mix.exs mix.exs
COPY mix.lock mix.lock
RUN chown myuser -R /home/myuser/code

USER myuser
RUN mix local.hex --force
RUN mix local.rebar --force

RUN mix deps.get
RUN mix deps.compile

USER root
COPY frontend/package.json frontend/package.json
COPY frontend/package-lock.json frontend/package-lock.json
RUN chown myuser -R .
USER myuser

RUN cd frontend && \
    npm install
