FROM elixir:1.5.2-alpine

ARG mix_env=dev

ENV PORT 4000
ENV MIX_ENV $mix_env
ENV MIX_ARCHIVES=/.mix
ENV MIX_HOME=/.mix

WORKDIR /code

RUN mix local.hex --force \
    && mix local.rebar --force

RUN apk add bash
RUN apk add --update nodejs nodejs-npm
RUN apk add --update inotify-tools

COPY mix.exs .
COPY mix.lock .

RUN mix deps.get
RUN mix deps.compile

COPY frontend/package.json frontend/package.json
COPY frontend/package-lock.json frontend/package-lock.json

RUN cd frontend && \
    npm install

COPY . .

RUN mix compile

RUN adduser -D user

RUN chmod 777 . frontend priv/static priv && \
    chmod 777 -R priv/static _build

USER user

ENTRYPOINT ["./docker-erlang-signals.sh"]
CMD ["phx.server"]
